const message = {
  isExisted: 'Dữ liệu đã tồn tại',
  notFound: 'Không tìm thấy',
  notEmpty: 'Không được để trống',
  isInt: (min, max) =>
    `Phải là kiểu số nguyên${min && max ? ` từ ${min} đến ${max}` : min ? ` lớn hơn hoặc bằng ${min}` : max ? ` nhỏ hơn hoặc bằng ${max}` : ''}`,
  isLength: (min, max) => `${min && max ? `Từ ${min} - ${max} kí tự` : min ? `Lớn hơn ${min} kí tự` : max ? `Nhỏ hơn ${max} kí tự` : ''}`,
  isIn: (values) => `Chỉ cho phép các giá trị: ${values.join(', ')}`,
  isString: 'Phải là chuỗi',
  isNumeric: 'Phải là kiểu số',
  isArray: 'Phải là kiểu mảng',
  isEmail: 'Sai định dạng email',
  incorrectPassword: 'Mật khẩu không đúng',
  unauthenticated: 'Chưa được xác thực',
  invalidToken: 'Token không hợp lệ',
  jwtHasExpiredPleaseLoginAgain: 'Token đã hết hạn. Vui lòng đăng nhập lại',
  invalid: 'Không hợp lệ',
  duplicate: 'Trùng lặp giá trị',
  alreadyExists: 'Giá trị đã tồn tại',
  notExist: 'Dữ liệu không tồn tại',
  isObject: 'Dữ liệu phải là kiểu Object',
  invalidPhone: 'Số điện thoại không hợp lệ',
  min: (min) => `Nhỏ nhất là: ${min}`,
  invalidDate: 'Ngày không hợp lệ',
  createdSuccessfully: 'Thêm thành công',
  createdFailure: 'Thêm thất bại',
  updatedSuccessfully: 'Cập nhật thành công',
  updatedFailure: 'Cập nhật thất bại',
  deletedSuccessfully: 'Xóa thành công',
  deletedFailure: 'Xóa thất bại',
  loginSuccessfully: 'Đăng nhập thành công',
  logoutSuccessfully: 'Đăng xuất thành công',
  youDoNotHaveAccess: 'Bạn không có quyền truy cập',
  isStrongPassword: 'Mật khẩu phải chứa ít nhất 8 ký tự bao gồm tối thiểu có 1 ký tự đặt biệt, 1 số, 1 chữ cái IN HOA và 1 chữ cái thường',
  isFloat: (min, max) =>
    `Phải là kiểu số thực${min && max ? ` từ ${min} đến ${max}` : min ? ` lớn hơn hoặc bằng ${min}` : max ? ` nhỏ hơn hoặc bằng ${max}` : ''}`,
  isURL: 'Phải là một URL hợp lệ',
  internalServerError: 'Lỗi máy chủ nội bộ',
  cannotDeleteAdmin: 'Không thể xóa quản trị viên',
  unauthorized: 'Không được phép',
  isDate: (format) => `Định dạng: ${format}`,
  passwordChangedSuccessfully: 'Thay đổi mật khẩu thành công',
  passwordMismatch: 'Mật khẩu không khớp',
  userNotFound: 'Không tìm thấy người dùng',
  oldPasswordIsIncorrect: 'Mật khẩu cũ không đúng',
  notTheSameOldPassword: 'Không được trùng với mật khẩu cũ',
  invalidData: 'Dữ liệu không hợp lệ',
  canDeleteYourself: 'Không thể xóa chính mình',
  invalidUrl: 'Url không hợp lệ',
  tooManyRequestsPleaseTryAgainLater: (minutes = null) => `Quá nhiều yêu cầu, vui lòng thử lại sau${minutes ? ` ${minutes} phút` : ``}!`,
  invalidUsernameOrPassword: 'Tài khoản hoặc mật khẩu không hợp lệ',
  noAccessTokenProvided: 'Không có access token được cung cấp',
  noRefreshTokenProvided: 'Không có refresh token được cung cấp',
  notFoundUser: 'Không tìm thấy người dùng',
  unauthorizedAccess: 'Truy cập trái phép. Vui lòng đăng nhập lại.',
  accountLocked: 'Tài khoản của bạn đã bị khóa do đăng nhập thất bại quá nhiều lần. Vui lòng thử lại sau 30 phút.',
  accountInactive: 'Tài khoản của bạn đã bị vô hiệu hóa. Vui lòng liên hệ quản trị viên.',
  isUsed: 'Đang được sử dụng',
  isSlug: 'Chuỗi phải là một slug hợp lệ (chữ thường, số, dấu gạch ngang)'
}

module.exports = { message }
